version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smartclinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password123@postgres:5432/smartclinic"
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm run start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres_data: